version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    volumes:
      - "./:/projects"
      - "./dockerfiles/tmp:/var/gunicorn"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - YOLP_APP_ID=$YOLP_APP_ID
    networks:
      virtual_hub:
          aliases:
            - gunicorn
    user: "${UID}:${GID}"

  web:
    container_name: web
    build:
      context: .
      dockerfile: dockerfiles/web/Dockerfile
    volumes:
      - "./dockerfiles/tmp:/var/gunicorn"
    ports:
      - "80:49152"
    depends_on:
      - app
    networks:
      virtual_hub:
        aliases:
          - nginx

networks:
  virtual_hub:
    driver: bridge
