version: "3"

services:
  flask:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./:/projects"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - YOLP_APP_ID=$YOLP_APP_ID
