version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./:/projects"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - YOLP_APP_ID=$YOLP_APP_ID
