import pytest
import requests

from ash_unofficial_covid19.scrapers.outpatient import ScrapeOutpatient


class TestScrapeOutpatient:
    @pytest.fixture()
    def excel_lists(self):
        excel_lists = [
            [
                "○",
                "○",
                "旭川",
                "市立旭川病院",
                "旭川市",
                "旭川市金星町１丁目１番６５号",
                "0166-24-3181",
                "かかりつけ患者の診療に限る",
                "○",
                "08:30:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "17:00:00",
                "08:30:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "17:00:00",
                "08:30:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "17:00:00",
                "08:30:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "17:00:00",
                "08:30:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "17:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "○",
                "○",
                "0",
                "○",
                "○",
                "○",
                "かかりつけ患者及び保健所からの紹介患者に限ります。\u3000https://www.city.asahikawa.hokkaido.jp/hospital/3100/d075882.html",
            ],
            [
                "○",
                "0",
                "旭川",
                "ＪＡ北海道厚生連\u3000旭川厚生病院",
                "旭川市",
                "旭川市１条通24丁目111番地",
                "0166-33-7171",
                "かかりつけ患者以外の診療も可",
                "0",
                "08:30:00",
                "～",
                "11:30:00",
                "00:00:00",
                "～",
                "00:00:00",
                "08:30:00",
                "～",
                "11:30:00",
                "00:00:00",
                "～",
                "00:00:00",
                "08:30:00",
                "～",
                "11:30:00",
                "00:00:00",
                "～",
                "00:00:00",
                "08:30:00",
                "～",
                "11:30:00",
                "00:00:00",
                "～",
                "00:00:00",
                "08:30:00",
                "～",
                "11:30:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
            ],
            [
                "○",
                "○",
                "旭川",
                "旭川赤十字病院",
                "旭川市",
                "旭川市曙１条１丁目1番１号",
                "0166-22-8111",
                "かかりつけ患者の診療に限る",
                "0",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "00:00:00",
                "～",
                "00:00:00",
                "○",
                "0",
                "0",
                "○",
                "○",
                "○",
                "「受診・相談センター」または保健所等の指示によら ず\n受診した場合，初診時選定療養費を申し受けます。\n当番制のため、不定期となっています。詳細はお問い合わせください。",
            ],
        ]
        return excel_lists

    def test_lists(self, excel_lists, mocker):
        responce_mock = mocker.Mock()
        responce_mock.status_code = 200
        responce_mock.headers = {"content-type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}
        mocker.patch.object(requests, "get", return_value=responce_mock)
        mocker.patch.object(ScrapeOutpatient, "_get_excel_lists", return_value=excel_lists)
        scraper = ScrapeOutpatient(excel_url="http://dummy.local")
        expect = [
            {
                "is_outpatient": True,
                "is_positive_patients": True,
                "public_health_care_center": "旭川",
                "medical_institution_name": "市立旭川病院",
                "city": "旭川市",
                "address": "旭川市金星町1丁目1番65号",
                "phone_number": "0166-24-3181",
                "is_target_not_family": False,
                "is_pediatrics": True,
                "mon": "08:30～17:00",
                "tue": "08:30～17:00",
                "wed": "08:30～17:00",
                "thu": "08:30～17:00",
                "fri": "08:30～17:00",
                "sat": "",
                "sun": "",
                "is_face_to_face_for_positive_patients": True,
                "is_online_for_positive_patients": True,
                "is_home_visitation_for_positive_patients": False,
                "memo": "かかりつけ患者及び保健所からの紹介患者に限ります。 https://www.city.asahikawa.hokkaido.jp/hospital/3100/d075882.html",
            },
            {
                "is_outpatient": True,
                "is_positive_patients": False,
                "public_health_care_center": "旭川",
                "medical_institution_name": "JA北海道厚生連旭川厚生病院",
                "city": "旭川市",
                "address": "旭川市1条通24丁目111番地",
                "phone_number": "0166-33-7171",
                "is_target_not_family": True,
                "is_pediatrics": False,
                "mon": "08:30～11:30",
                "tue": "08:30～11:30",
                "wed": "08:30～11:30",
                "thu": "08:30～11:30",
                "fri": "08:30～11:30",
                "sat": "",
                "sun": "",
                "is_face_to_face_for_positive_patients": False,
                "is_online_for_positive_patients": False,
                "is_home_visitation_for_positive_patients": False,
                "memo": "",
            },
            {
                "is_outpatient": True,
                "is_positive_patients": True,
                "public_health_care_center": "旭川",
                "medical_institution_name": "旭川赤十字病院",
                "city": "旭川市",
                "address": "旭川市曙1条1丁目1番1号",
                "phone_number": "0166-22-8111",
                "is_target_not_family": False,
                "is_pediatrics": False,
                "mon": "",
                "tue": "",
                "wed": "",
                "thu": "",
                "fri": "",
                "sat": "",
                "sun": "",
                "is_face_to_face_for_positive_patients": True,
                "is_online_for_positive_patients": False,
                "is_home_visitation_for_positive_patients": False,
                "memo": "「受診・相談センター」または保健所等の指示によら ず 受診した場合,初診時選定療養費を申し受けます。 当番制のため、不定期となっています。詳細はお問い合わせください。",
            },
        ]
        assert scraper.lists == expect

    def test_get_medical_institution_list(self, excel_lists, mocker):
        responce_mock = mocker.Mock()
        responce_mock.status_code = 200
        responce_mock.headers = {"content-type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}
        mocker.patch.object(requests, "get", return_value=responce_mock)
        mocker.patch.object(ScrapeOutpatient, "_get_excel_lists", return_value=excel_lists)
        scraper = ScrapeOutpatient(excel_url="http://dummy.local")
        expect = ["市立旭川病院", "JA北海道厚生連旭川厚生病院", "旭川赤十字病院"]
        name_lists = scraper.get_medical_institution_list()
        assert name_lists == expect
